import React from 'react';
import './About.css';

const About = () => (
    <section id='about'>
        <div className='content' id="about-content">
            <h3>POWERING OUR FUTURE PLANET</h3>
            <p>How will we power our future planet?  And, how will our energy choices reshape the the Earth's geography?</p>
            <p>Energy has been at the center of human progress since we first mastered fire.  Over the millennia, humanity's energy innovations and strategies have profoundly impacted the geography of our planet.  Felling trees for the burning of wood and the creation of wood charcoal led to deforestation on epic scales as we sought to warm ourselves, cook our food, and smelt metals.  Whales were slaughtered by the tens of thousands in part to light lamps around the world.  The dawn of modern coal mining helped our forests rebound in some places, but created geographies of life choking emissions while it fueled industrialization and the growth of railways to distant frontiers.  The commercial exploitation of oil resources paired with the combustion engine enable widespread electrification as well as automobiles and airplanes that empowered humans to go anywhere the fuel supply chain allowed them to.  Nuclear power allowed navies to project power around the world without need for refueling, and provided additional base load to the civilian electrical power grid.  Renewable energy sources such as solar, wind and thermal are now changing the geography of energy, as they are liberated from costly and dirty fuel supply chains.  As the economic models of each of these energy sources are shaped by continued technological innovation, there will no doubt be a massive convulsion in energy generation, distribution, and consumption that will remake the geography of our planet yet again.</p>
            <p>Where will our future energy supplies be located, and how will new distribution systems link different regional geographies in to the world energy system?  Where will people realize energy efficiencies, and consume less per capita than today?  Where will they be tied to inefficient energy legacies until the distant future?  Who will finance and control our future energy supplies, and how will their choices impact issues of sustainability and social justice on a local, regional and global scale?  How should we think about the environmental consequences of our actions as it relates to different key ecological regions?  How will our choices affect human health in different parts of the world?  Will utopian or dystopian visions of our future energy landscape take hold, or will we simply find ourselves "muddling through?"</p>                
            <p>How we think about energy has, and always will be central to the future geography of our planet.  As such, in 2018, the next installment in the American Geographical Society's multi-year strategic dialog will focus on the the vital trends in energy that will reshape the geography of our planet will focus.  Geography2050: Powering our Future Planet (2018.geography2050.org) will bring together thought leaders from government, industry, academe, the social sector and education to help us think through how innovations in energy will help us navigate a perilous future that legacy energy sources and strategies have made probable.</p>
            <p>Mark your calendars today for November 15-16, 2018 to join us in New York City, at Columbia University, and help shape this critical discussion.</p>
            <p>If you have ideas on speakers or interest in sponsoring, please contact us at Geography2050@americangeo.org today!</p>
        </div>
    </section>
);

export default About;
